bh - Restrict name for Personal Schedule to 15 chars or less
ucsb-cs156-f22/f22-5pm-courses pull request #10
Opened 2022-11-17 02:12 UTC by bhuang01

In this PR, we add a restriction to the PersonalSchedule name parameter - name should be 15 characters or less. Closes #8 

<img width="563" alt="image" src="https://user-images.githubusercontent.com/44068328/202337531-144a81d7-6d15-42dc-863e-4559ef69f316.png">

2022-11-17 04:12 UTC, pconrad requested changes
LGTM... but if you want me to merge this, please modify issue 8 so that it only covers the frontend.  Right now, this PR says "closes #8", but issue 8 is worded as:

```
Make ALL of both the frontend and backend changes so that names cannot be longer than 15 characters.
```

As I detailed on your slack channel, there's some separate backend work needed to fully implement this.  That can do in a separate issue and separate PR (that's my recommendation).

2022-11-17 04:12 UTC, pconrad commented
Also please add your team label.

2022-11-17 04:36 UTC, bhuang01 commented
> LGTM... but if you want me to merge this, please modify issue 8 so that it only covers the frontend. Right now, this PR says "closes #8", but issue 8 is worded as:
> 
> ```
> Make ALL of both the frontend and backend changes so that names cannot be longer than 15 characters.
> ```
> 
> As I detailed on your slack channel, there's some separate backend work needed to fully implement this. That can do in a separate issue and separate PR (that's my recommendation).

Updated issue #8 - only frontend changes. New issue #11 is targetting backend for the name length issue

2022-11-17 16:28 UTC, pconrad approved these changes
LGTM!  I'll test it on your qa site before merging

2022-11-17 16:35 UTC, pconrad commented
Deployed at https://f22-5pm-2-courses.herokuapp.com/ but can't test because OAuth is misconfigured.

2022-11-18 02:22 UTC, hauntedghosts approved these changes
Tested branch locally on my machine, Character limit feature works. LGTM

2022-11-18 20:36 UTC, andrewpengucsb approved these changes
Deployed to qa heroku, LGTM

2022-11-18 20:37 UTC, merged