sc - create personal schedules dropdown component
ucsb-cs156-f22/f22-5pm-courses pull request #39
Opened 2022-11-27 19:46 UTC by sophiacheng01

In this PR, we add the code to create a dropdown component along with tests using fixtures. 

To run my code and visualize the component clone my repo, cd into frontend, and run npm storybook.

Closes #6

2022-11-28 15:58 UTC, hauntedghosts submitted a review, later dismissed
Tested locally and on QA and produced the same result, LGTM

2022-11-28 22:51 UTC, pconrad requested changes
One small issue in the fixtures.. otherwise, lgtm

2022-11-28 22:51 UTC, pconrad commented on frontend/src/fixtures/personalScheduleFixtures.js
> +          "quarter": "20229",
20229 isn't a valid quarter... the last digit should be 1 for Winter, 2 for Spring, 3 for Summer, and 4 for Fall.   I think you probably want to change this to 20224

2022-11-28 22:52 UTC, pconrad requested changes

2022-11-28 22:52 UTC, pconrad commented on frontend/src/fixtures/personalScheduleFixtures.js
> +          "quarter": "20229",
```suggestion
          "quarter": "20224",
```

2022-11-29 03:09 UTC, pconrad approved these changes
LGTM!

2022-11-29 03:09 UTC, merged