James backend quartersubjects
ucsb-cs156-f22/f22-5pm-courses pull request #50
Opened 2022-11-29 21:42 UTC by Jameszhao1103

Closes #24 

Add new backend job that takes only a quarter as it's parameter, not a quarter and subjectArea
Inside the job logic, get the list of subject areas, and the iterate through those, making one API call at a time, and then updating the MongoDB database for each one.
It may be helpful to put out a log message for each subject area as it is updated with the number of courses added, updated, and a count of errors.
For testing, you can mock a list of subject areas that is MUCH shorter so that the test log output doesn't have to be super long.
Involves a new Job type, and a new entry in the JobsController.

Jacoco tests passed:
![jacoco](https://user-images.githubusercontent.com/62822602/204654126-93271cbe-28fe-40ae-89bc-e4ad2ea09b99.jpg)

Pitest Mutation tests passed:
![Pitest](https://user-images.githubusercontent.com/62822602/204654178-766e3723-dfcb-45f4-89bf-172b8723e646.jpg)

Heroku successfully deployed:

2022-11-29 22:01 UTC, tallyhawley requested changes
Could you return .env.SAMPLE to its original state? Otherwise it looks great

2022-11-29 22:26 UTC, Jameszhao1103 commented
> Could you return .env.SAMPLE to its original state? Otherwise it looks great

OK I changed .env file. Now it should match the original one

2022-11-29 22:49 UTC, liamjet approved these changes
LGTM

2022-11-29 23:11 UTC, pconrad approved these changes
LGTM.. will test on QA

2022-11-30 05:54 UTC, pconrad approved these changes
LGTM

2022-11-30 05:57 UTC, merged