Add frontend support for new job which takes only a quarter as its parameter
ucsb-cs156-f22/f22-5pm-courses pull request #52
Opened 2022-11-30 01:41 UTC by drikdrok

Resolves #25 

* Adds new job form for updating courses by quarter only

![image](https://user-images.githubusercontent.com/8681057/204686666-602c6f35-a6f0-41ef-b401-f63a7f3bccaa.png)

2022-11-30 09:58 UTC, tallyhawley submitted a review, later dismissed
lgtm

2022-12-01 01:44 UTC, pconrad approved these changes
LGTM.. will test on qa

2022-12-04 23:49 UTC, pconrad requested changes
Please consider making the scope of Stryker exclusions as small as possible, as illustrated in this PR: https://github.com/ucsb-cs156-f22/f22-5pm-courses/pull/57

2022-12-04 23:49 UTC, pconrad commented on frontend/src/main/components/Jobs/UpdateCoursesByQuarterJobForm.js
> +  // Stryker disable all : not sure how to test/mock local storage
This should be followed by 
// Stryker enable all 
after the line of code that does local storage.

2022-12-04 23:49 UTC, pconrad commented on frontend/src/main/components/Jobs/UpdateCoursesByQuarterJobForm.js
> +  // Stryker disable all : Stryker is testing by changing the padding to 0. But this is simply a visual optimization as it makes it look better
Same as above... it's ok to invoke this for the part of the code that needs Stryker disabled... but you need to confine this to the smallest possible scope.

2022-12-04 23:49 UTC, pconrad commented on frontend/src/main/components/Jobs/UpdateCoursesByQuarterJobForm.js
> +  // Stryker disable all : Stryker is testing by changing the padding to 0. But this is simply a visual optimization as it makes it look better
In https://github.com/ucsb-cs156-f22/f22-5pm-courses/pull/57 I suggest what this might look like.

2022-12-06 03:43 UTC, pconrad approved these changes
LGTM

2022-12-06 03:44 UTC, merged