kd - issue #45: ensured uniqueness for PSCourse post. Added tests.
ucsb-cs156-f22/f22-5pm-courses pull request #53
Opened 2022-11-30 01:53 UTC by dengkevin

In this PR, I check if enrollCdPrimary is not already in the personal schedule before adding it (ensuring no duplicate PSCourse posts). I also add test functionalities for the code I added.

2022-11-30 02:09 UTC, eduglt commented on src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
> +        when(coursesRepository.findByPsIdAndEnrollCd(eq(1L), eq("08326"))).thenReturn(Optional.empty());
I think the enroll code should be "08292" since that's the primary enroll code and what gets checked in the `postCourses` implementation.

2022-11-30 02:09 UTC, eduglt commented on src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
> +        when(coursesRepository.findByPsIdAndEnrollCd(eq(1L), eq("63388"))).thenReturn(Optional.empty());
I think the enroll code should be "63370" since that's the primary enroll code and what gets checked in the postCourses implementation.

2022-11-30 02:17 UTC, eduglt approved these changes
LGTM, thanks for changes!

2022-12-04 23:55 UTC, pconrad approved these changes
LGTM

2022-12-05 00:43 UTC, pconrad requested changes
Definitely does NOT look good to me.

2022-12-05 00:43 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
> +    if (coursesRepository.findByPsIdAndEnrollCd(psId, enrollCdPrimary).isPresent()) {
It's just embarrassing to see indentation issues this blatant in a PR that you are asking to merge into main.

Have we not taught you better than this .. not just in this course, but in all of your UCSB coding courses up to this point?

2022-12-06 03:45 UTC, pconrad approved these changes
Much better :-)

2022-12-06 03:46 UTC, merged